### ISSUE TITLE
Remove AngularJS dependency from LaxarJS core

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#216]
### Rationale

Currently the LaxarJS runtime has a dependency to AngularJS. The reasons are mostly historical:

   * rich DOM API provided by `ng.element`: useful with MSIE7/8 (no longer supported by LaxarJS nor AngularJS)
   * $http and $q were useful to implement async loading
   * modules and $inject were useful to implement easily mocked modules and services
   * routing out-of-the-box available
   * powerful directives like ngInclude
   

While these benefits still exist, there are lightweight alternatives:

   * DOM has become better (querySelector etc).
   * ES6 standardizes Fetch and Promise APIs for async stuff, polyfills available
   * ES6 (or even AMD) modules can be mocked as well, if they are stateless and follow a factory-style pattern (receiving all runtime dependencies as arguments)
   * many other micro-libs for routing, focussing only on this task (in fact AngularJS will itself abandon its current routing implementation for a [new alternative](https://github.com/angular/router))
   * identified as performance bottleneck, we already mostly removed usage of such builtin directives

Finally, we used to write widgets with AngularJS by default. But this is no longer automatically the case. We already support using other MVC technologies, so why give AngularJS special treatment? When AngularJS 2 arrives, we will have two options:

   * move to AngularJS 2.x and replace the existing AngularJS 1.x integration
   * remove Angular usage from core and turn AngularJS 1.x support into an external integration plugin. Do the same for Angular 2.x
 
While the second option does not necessarily allow for an application to use both AngularJS 1.x and 2.x at the same time, it would at least _allow the application author to decide_ which version to use.

### Steps

Most of the actual AngularJS _integration_ is already living within the AngularJS widget technology adapter. The rest is mainly _using_ angular APIs and services to perform resource loading, service injection  etc. So, the steps might look like this:

  
   1. [x] Move the AngularJS adapter into a separate project
   2. [x] Replace $q with ES6-Promise
   3. [x] Replace $http with ES6-Fetch
   4. [x] Replace all `ng.element` calls with DOM API access
   5. [x] Evaluate and integrate a replacement for the AngularJS router
   6. [x] Provide an integration API for widget areas (move the current `ax-widget-area` directive to the AngularJS integration project)
   7. [x] Move the directives `ax-id` and `ax-for` to individual controls, possibly also within the integration project.
   8. [x] Define a fixed set of injections that LaxarJS provides to *any* integration technology, and remove usage of AngularJS DI. 
   9. [x] Turn services into AMD factory modules (ES5 or compiled from ES6)

Because the individual steps are relatively complex, we might treat them as individual tickets. Any of these steps should probably be performed _after_ branching of `master-1.x`. More steps will possibly be identified before this ticket is completed.

**Comment by alex3683** [comment]
Implemented on `master` (`v2.0.0`). _(This issue was resolved in form of many other issues, hence there is no single commit referencing it)_

### Breaking Change

AngularJS was completely removed from the LaxarJS core. The widget adapter for widgets based on AngularJS 1.5.* was extracted into its own [repository](https://github.com/LaxarJS/laxar-angular-adapter/) and has to be loaded manually when bootstrapping the app. Further information can be found at this repository.
