### ISSUE TITLE
api docs: add api doc where missing and correct where it is (now) wrong

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#276]
For some new artifacts api doc is completely missing and in some cases it is now wrong (e.g. method signatures changed and former AngularJS stuff like $q and $http was removed).

**Comment by x1B** [comment]
- [ ] Here, we should also use the upgrade information from #333 to extend/simplify the visibility manual.

**Comment by jpommerening** [comment]
- [ ] don't forget to generate API docs for [`laxar.js`](/LaxarJS/laxar/blob/master/laxar.js), `bootstrap()` in particular (missing in all released versions)

**Comment by alex3683** [comment]
- [ ] Change `@memberOf` to `@memberof` where wrong.

**Comment by alex3683** [comment]
@x1B : Please document `axTooling` in `widget_services.js` and the tooling API itself. Or at least enable me doing it ❣️

**Comment by alex3683** [comment]
@x1B You'll find my changes on `feature/276-api-doc-rebase` branch.

**Comment by x1B** [comment]
Added another ticket for the tooling docs (#404)

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
