### ISSUE TITLE
karma: re-enable chrome and junit reporting

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#314]
When transitioning to webpack-based builds, I accidentally removed junit reporting and the Chrome-testing from our karma configuration.

- [ ] re-enable junit reporting
- [ ] simplify `karma.config.js`
- [ ] also run on Chrome, not just PhantomJS (there is [a tutorial](http://swizec.com/blog/how-to-run-javascript-tests-in-chrome-on-travis/swizec/6647) for this)

**Comment by x1B** [comment]
Fixed on `master` (`v2.0.0`).
