### ISSUE TITLE
eslint: additional validations

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#315]
Add additional eslint options

**Comment by x1B** [comment]
```json
      "valid-jsdoc": "warn",
```

**Comment by alex3683** [comment]
- [x] `"valid-jsdoc": "warn"`
- [ ] `"no-loop-func": "error"`
- [ ] `"no-underscore-dangle": "warn"`
- [ ] `"prefer-arrow-callback": "warn"`
- [ ] `"prefer-rest-params": "warn"`
- [ ] `"prefer-spread": "warn"`
- [ ] `"prefer-template": "warn"`
- [ ] `"rest-spread-spacing": [ "warn", "never" ]`
- [ ] `"sort-imports": ?`

**Comment by x1B** [comment]
Our JS-Doc style so far:

```js
      "valid-jsdoc": [ "warn", {
         "requireReturn": false,
         "preferType": {
            "object": "Object"
         },
         "prefer": {
            "returns": "return",
            "arg": "param",
            "argument": "param"
         }
      } ],
```

**Comment by alex3683** [comment]
Implemented on `master` (`v2.0.0`)
