### ISSUE TITLE
file resource provider: simplify listing configuration

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#321]
Currently, LaxarJS file listings are passed as part of the configuration, and application authors have to specify what root paths are covered by the file listings.

We want to change this so that
- [x] the listings bundle is passed directly to laxarjs bootstrap, and not part of the configuration
- [x] no more listing roots need to be configured: the listings already cover everything that the file resource provider might be asked for, because they are generated based on an application's artifacts and themes
- [x] for the same reason, no HTTP HEAD checks are needed anymore

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
