### ISSUE TITLE
flow service: collected issues

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#373]
- [x] _2.x:_ Check the `target` of `didNavigate` events: Currently if a place instead of a target is used as the value of the `target` field in `navigateRequest` events, this is also used as the topic of the `didNavigate` event. Since this violates the constraints of the topic syntax and is no target at all, we'd rather leave the value for `target` empty. In case of a direct request (i.e. the URL changes) `_self` is used, which is also incorrect (#381).
- [x] _2.x:_ Make `target` and `place` explicit in `navigateRequest` events: Currently only `target` is supported, which could be a place or a target. This should be more explicit, so that either `target` or `place` is allowed, but each is only interpreted as what it name says it is. If both are given, this incident should be logged, but the `place` should eventually be favored, since its more explicit (#381).
- [x] _2.x:_ When validating the `flow.json` against the flow JSON schema, defaults should directly be applied. Currently defaults are set manually (#380).
- [ ] For _1.x:_ after a redirect we should call [`$location.replace()`](https://docs.angularjs.org/guide/$location#replace-method) to replace the entry on the history stack instead of putting it on top. Otherwise redirects create two entries and thus break the back button. For _2.x_ we should check the according api in `page.js` (#382) (*edit:* the issue does not exist in page.js, so nothing to do for _2.x_).
- [ ] _1.x:_ If the application uses a non empty base for routing in html5 mode, that base is added as prefix to the routes but also to the place name within the `didNavigate` event. This leads to inconsistency between configured places and places within the event. The context (i.e. the base) should never be part of the places. Have a look at `flow.spec.js` for an example (#383).

**Comment by x1B** [comment]
2.x: we probably also need to double-encode slashes in path segments, like with AngularJS in v1.x (cf #379). When navigating to a URL, the browser will decode single-encoded slashes before page.js starts the route matching process, causing those slashes to break the match.

**Comment by x1B** [comment]
_Updated description and comments:_ added references to individual tickets.

**Comment by x1B** [comment]
_Closing as duplicate:_ remaining issues are tracked in their respective issues
