### ISSUE TITLE
v2.x: Update JSON schemas

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar#405]
Related to #380 but needs to be resolved independently (even if we don't resolve #380 in 2.0).

The JSON schemas in `static/schemas` are outdated.

- [x] The widget schema does not contain the new keys for assets yet.
   - `assets`, `assetsForUrl`, `themedAssets` and `themedAssetsForUrl` are missing
   - `styleSource` and `templateSource`, missing as well

- [x] There is no schema for controls yet (supporting the same keys as widgets, but without features).

- [x] Layouts and themes can have a descriptor as well, probably supporting only `name`, `description`, `styleSource` and `templateSource`.

- [x] I think the flow and page schema are up to date (esp. considering `page.js`), but correct me if I'm wrong.

- [x] Can we make the schemas `.json` files again? That way they can be more easily consumed by `laxar-tooling` (see [#10](/LaxarJS/laxar-tooling/issues/10)) via its `readJson` callback.

~@alex3683, @x1B: Question regarding `styleSource` and `templateSource`: should those have the default built into the schema, or should the default value be provided by the code that handles the assets?~

**Comment by x1B** [comment]
@jpommerening I think that for documentation purposes, it would be nice to store the default in the schema. But only if we also read it from there.

**Comment by jpommerening** [comment]
Now I'm confused. If we store it in the schema and validate according to the schema (with ajv conflating validation and default substitution) there won't be a need to handle the default in the runtime, will there? We can just expect the fields to be set to whatever the schema specifies as a default.

**Comment by x1B** [comment]
@jpommerening that's true. Wasn't quite sure if the defaults are already being applied for the widget schema.

**Comment by jpommerening** [comment]
Oh dear. It really was not until I was extending the schema and typing `"default": "css/` that I noticed what was wrong. Since the default style- and template- file names include the widget name, there's no way to specify that in the schema (unless JSON schema supports some kind of reference and string interpolation magic, which I hope it doesn't).
Sorry for the noise everyone 😅

**Comment by x1B** [comment]
oh my  :space_invader:

**Comment by jpommerening** [comment]
I just pushed what I believe are the updated schemas.
Note: I changed the page_loader and flow_controller files to load with the JSON loader. This is currently a breaking change, since it requires the user to install the JSON loader.

However:
- `laxar-loader` depends on the `json-loader` so it should already be present
- the built `laxar.min.js` should contain the bundled schemas
- we'll probably remove runtime-validation anyway

**Comment by x1B** [comment]
@jpommerening I'll have a look at this in one of our applications

**Comment by x1B** [comment]
@jpommerening hmm, when running the tests, it looks like the JSON-loader is applied twice.

**Comment by x1B** [comment]
Tests are fixed. Also, I relaxed the schema a bit in preparation for (#380), allowing dashes in IDs, since they will now be generated by LaxarJS/laxar-tooling.

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
