### ISSUE TITLE
Documentation: correct some small bugs

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/laxar#449]
- [x]  [Widgets and Activities](https://github.com/LaxarJS/laxar/blob/master/docs/manuals/widgets_and_activities.md#implementing-a-controller): In the code example for the controller the line `Controller.$inject = [ '$scope' ];` is missing.
- [ ] [Widgets and Activities](https://github.com/LaxarJS/laxar/blob/master/docs/manuals/widgets_and_activities.md#implementing-a-controller): In the last line 
```
export const name = ng.module( 'shoppingCartWidget' )
   .controller( 'ShoppingCartWidgetController' ).name;
``` 
the second parameter is missing: 
```
export const name = ng.module( 'shoppingCartWidget', [] )
   .controller( 'ShoppingCartWidgetController' ).name;
```

- [x] [Widgets and Activities](https://github.com/LaxarJS/laxar/blob/master/docs/manuals/widgets_and_activities.md#widget-responsibilities): `As a rule of the thumb,` should be `As a rule of thumb,`

**Comment by x1B** [comment]
Fixed on `master` (`v2.0.0`).
